### ISSUE TITLE
Differences from the default Markdown field?

### ISSUE THREAD

**Issue by niladam** [dinandmentink/nova-markdown#1]
Hello,

I'd like to know what the differences are from the native Markdown field that's included in Nova?

In case you're unaware, here's a link: https://nova.laravel.com/docs/1.0/resources/fields.html#markdown-field

**Comment by dinandmentink** [comment]
Fair question. I'll make a note to add this to the readme.

They are similar in that both of them perform no transformations on the input and simply store it (in usually a TEXT column). Both of them offer inline text highlighting of markdown text.

Where they differ is that the default markdown field offers highlighting and a toolbar for strong, italic, image and link. This markdown editor, based on [simplemde](https://simplemde.com/) offers also headings, blockquotes, ordered list and unordered list.

**Comment by niladam** [comment]
Thank you @dinandmentink for your reply. And yes, I think this should be added to the readme. Also, can you please tell me how you handle images? Are they uploaded to the server like with Trix?

I haven't had a chance to look into the package yet, but I will try it out next week and provide you with my feedback. I used simplemde in the past with backpack and I loved the clean interface it provides. Hopefully, some of its options will also be (if they're not already) available in this package. 

Thank you for your work and for sharing the package!

**Comment by dinandmentink** [comment]
At the moment there is no image handling available. I would love to have it the way github does, with the auto handling of dropped images. But for now it does what I need it to do.

Feel free to open a PR if you would like to contribute. I'll add some more details to the readme. It's all still very early days.
