### ISSUE TITLE
Laravel 9 support is available as v3.0.1

### ISSUE THREAD

**Issue by dinandmentink** [dinandmentink/nova-markdown#19]
Quick note for all those who are waiting for this. I'm currently working on laravel 9 support.

**Comment by dhonions** [comment]
Thanks! Looking forward to it 👍

**Comment by dinandmentink** [comment]
For those reading. Sorry, the world exploded and I was away. I have not forgotten or abandoned this project, but still have to fix the laravel 9 support. Sorry to keep you all waiting.

**Comment by dinandmentink** [comment]
Alright. Thanks for waiting. I have just released version `v3.0.1` which works with laravel v9.x. I have tested it locally and it works, but hasn't been verified in production yet, however I would be comfortable deploying this myself.

v3.x will also require spatie/image v2.x. To me it seems spatie/image v1.x doesn´t work with larave v9.x anyways. 

If you find any problems please let me know in an issue or submit a pull request.

Sorry for being this slow, but the last year has been hectic and /gestures to world outside/. 

Edit: I'll update the readme to display the laravel/php version constraints.
