### ISSUE TITLE
Navbar over fullscreen editor

### ISSUE THREAD

**Issue by OliverZiegler** [dinandmentink/nova-markdown#2]
When entering fullscreen mode, the nova navbar will overlay the simplemde navbar.

Navbar is `.z-20` and the searchbar is `.z-50` at the time of writing.

So when in full screen the editor should at least be `z-index: 51` I suppose.

**Comment by dinandmentink** [comment]
Thanks for reporting. I will try to fix this next friday.

Feel free to open a pullrequest if you need it earlier.

**Comment by Fot0n** [comment]
@dinandmentink, please fix it.

**Comment by dinandmentink** [comment]
I haven't gotten around to it, it's on my list.

Feel free to open a pr.

**Comment by dinandmentink** [comment]
Should be fixed in latest release.
