### ISSUE TITLE
Follow default behaviour of official markdown field in index and show view

### ISSUE THREAD

**Issue by ziming** [dinandmentink/nova-markdown#3]
Hi there,

Nice package. It will be great if it hide itself in index view by default and follow Nova default markdown field in show view

https://nova.laravel.com/docs/2.0/resources/fields.html#markdown-field

Thanks a lot!

**Comment by dinandmentink** [comment]
Thanks for the suggestion!

I think it's a valid idea and have made a note to get back to this when I have some time. Might take a while. Feel free to open a PR if you want to do it yourself.

**Comment by ziming** [comment]
I can wait for you. no worries :)

**Comment by dinandmentink** [comment]
It took some time to get around to researching this.

I have made this change for v0.4.2. The package will no longer show by default on index, but it can be shown on the index for those that wish to do so.
