### ISSUE TITLE
easy-markdown-editor.tk

### ISSUE THREAD

**Issue by Fot0n** [dinandmentink/nova-markdown#30]
You won't believe it, but the link to the demo version of EasyMDE specified in the Readme again leads to a malicious site. It may be worth replacing it with a repository.

**Comment by dinandmentink** [comment]
Thanks for the headsup, I'll change it immediately. The [easymde repo](https://github.com/Ionaru/easy-markdown-editor) does also itself link to this website. I'll flag it. 

Does make me wonder how maintained easymde is; I might consider an alternative although they are sparse.

**Comment by dinandmentink** [comment]
Changed the url. Thanks for flagging this!
